const ProjectsPage = () => {
  return (
    <>
      <h3>Projects</h3>
      <hr />
      {/* (h5{Projet n°$}+p>lorem*5)*5 */}
      <h5>Projet n°1</h5>
      <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus cumque veritatis dolorem autem laboriosam qui? Deleniti quas vero molestiae minima placeat repellendus corrupti iure. Facere suscipit nemo error esse recusandae.</span><span>Quidem quasi dolores qui sapiente ipsum, iste fugiat sint molestiae aperiam reprehenderit ratione rerum mollitia labore libero ea consectetur eligendi rem officiis voluptas officia. Facere totam fuga laudantium debitis dolor!</span><span>Nihil corrupti qui, cum soluta sapiente non deserunt repudiandae voluptas numquam iure veritatis. Reprehenderit illo ut voluptatum? Quibusdam, doloribus consequuntur minus debitis odit, omnis sint, nam facere nobis explicabo quam?</span><span>Atque distinctio, ipsum inventore corporis nulla, ut magni eum deserunt autem molestias optio nostrum repellat. Reiciendis quod eveniet quibusdam architecto natus pariatur laborum tenetur dolores, quis numquam explicabo quia soluta.</</p>
      <h5>Projet n°2</h5>
      <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure esse maiores ab veniam repellendus, quam eaque non odit earum mollitia ullam molestiae? Autem commodi praesentium provident corrupti harum ab iusto.</span><span>Officiis accusantium praesentium debitis placeat! Dolorum odio provident nihil nulla ut dignissimos culpa nemo perspiciatis eos aspernatur repudiandae voluptate, commodi consectetur temporibus, ab ullam tempore impedit in corrupti omnis quis?</span><span>Vel at mollitia exercitationem ipsum ipsam quisquam provident quo rem eum, quae repellat illo possimus libero adipisci iste perferendis illum, temporibus labore reprehenderit magnam perspiciatis? Optio rerum itaque nam voluptate.</span><span>Nostrum fuga nesciunt vitae? Incidunt eligendi dolores dicta distinctio itaque autem blanditiis quibusdam voluptate nobis cumque ea in maxime ab omnis, rerum modi atque odio accusantium excepturi inventore quia aut?</span><span>Dicta dolor similique pariatur ratione facilis? Dolore dolor, magni maxime optio itaque molestias inventore facere pariatur vel quidem quam, voluptatibus vero rerum beatae molestiae labore facilis voluptates, eius doloribus debitis.</span></p>
      <h5>Projet n°3</h5>
      <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione eum non eos, fuga unde dolorem assumenda rem voluptate, sunt id a veniam cum possimus, doloribus accusantium et velit delectus saepe?</span><span>Magnam delectus asperiores consectetur, obcaecati laborum quae perferendis ex explicabo aspernatur, maxime architecto veritatis sit? Facilis odio aspernatur harum voluptatem numquam repudiandae nulla rem quaerat. Quis ab perspiciatis quisquam molestiae?</span><span>Ipsam, qui. Numquam veritatis iusto voluptatibus assumenda culpa soluta vitae sed atque! Esse autem velit quibusdam perferendis cum distinctio quasi aut veritatis iste iusto! Impedit, illum vel. Nihil, soluta alias?</span><span>Error fugiat optio quis magni deserunt praesentium alias beatae! Culpa ut vero, iure molestiae, optio officiis laboriosam odio, libero excepturi non obcaecati. Et fuga tempora eum quod sit accusamus minima?</span><span>Soluta, voluptate ex dicta quae sit est natus doloribus, temporibus dolore similique, incidunt dolor totam maiores cum minima beatae culpa fugiat id doloremque atque eveniet obcaecati? Ad mollitia odio cum.</span></p>
      <h5>Projet n°4</h5>
      <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, voluptates aperiam temporibus voluptate modi, optio accusantium provident culpa dicta, itaque repellendus possimus inventore quis! Et consectetur quibusdam iste atque iusto!</span><span>Quo hic cupiditate quae, expedita illo eligendi natus laudantium enim non officia assumenda similique quod ipsum at. Sed explicabo molestias sunt eum iusto ut assumenda quibusdam? Animi, tempora. Sint, cumque.</span><span>Possimus saepe assumenda nisi magni sint illo incidunt sed. Ducimus cupiditate quae illo doloribus maxime nobis accusamus blanditiis nam quidem iure fugit, deserunt asperiores, expedita necessitatibus labore. Blanditiis, sunt consequatur?</span><span>Dignissimos architecto, officia doloremque suscipit nam quidem dolore aliquam eos eligendi animi quo harum sit, optio excepturi dicta libero adipisci tenetur alias dolorem perferendis, nulla ipsum ad. Accusantium, excepturi iure!</span><span>Magni dolorem in ut deserunt odit id cumque doloribus. Dolorum animi reprehenderit quae commodi repudiandae facilis cum perferendis porro ullam numquam expedita iusto delectus eveniet necessitatibus voluptate alias, unde amet?</span></p>
      <h5>Projet n°5</h5>
      <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae ducimus, optio dolorem, magni laudantium fugiat nemo laborum molestiae hic sapiente, reiciendis vel qui ab tenetur a enim nisi et. Autem.</span><span>Molestiae recusandae nam dolores sit perspiciatis illo, quia libero dolore provident expedita! Atque obcaecati itaque aliquid possimus. Qui officiis quaerat, neque voluptatum blanditiis, tempora vel reiciendis maxime quae praesentium assumenda.</span><span>Amet vitae accusamus cumque, recusandae, voluptates corrupti cum esse deleniti atque possimus architecto minima exercitationem enim optio nisi soluta inventore laboriosam adipisci ex aut ipsum. Quidem, soluta. Fuga, vitae voluptates.</span><span>Iure molestias molestiae numquam neque ab. Eos facere harum libero voluptate! Tenetur officiis quod nulla ipsa non ut voluptatibus perspiciatis voluptates pariatur dolores sed placeat numquam autem itaque, dolor vitae.</span><span>Molestias magni, veniam accusantium aperiam fugiat repudiandae possimus voluptatum exercitationem saepe iure repellat nobis eaque illum dolorem? Nobis, minus, ut voluptate quae esse cum sunt cumque, optio nesciunt quas doloremque.</span></p>
    </>
  )
}

export default ProjectsPage
